function h = sptPALM_components(h, Side_Border, Height_Border, ControlPannel_Width, ControlPannel_Height)

%% GUI: Default sizes and properties

FontSize = 8;
PushButtonSize_Pannel1 = [150,25];
PushButtonSize_Pannel3 = [120,27];
PushButtonSize_Pannel5 = [120,27];
PushButtonSize_Pannel6_small = [150,27];
PushButtonSize_Pannel6_long = [250,27];

EditSize = [35, 21];
CheckBoxSize = [15, 21];

PopupmenuSize = [120, 25];

TextFolderName = [ControlPannel_Width-2*Side_Border, 30];
TextSize_Pannel1 = [80 15];
TextSize_Pannel2 = [240 15];
TextSize_Pannel4 = [180 15];
TextSize_Pannel5 = [110 15];
TextSize_Pannel6_small = [90 15];
TextSize_Pannel6_long = [120 15];

SliderSize_Pannel5 = [280, 20];

PanelBorder_top = 20;
PanelBorder_bottom = 5;
InterPanelDistance_Height = 10;
InterPanelDistance_Width = 10;

Panel_Line_Height = round((ControlPannel_Height-2*Height_Border-5*InterPanelDistance_Height-5*PanelBorder_top-5*PanelBorder_bottom-TextFolderName(2))/22);

PanelWidth_WorkSpace_1 = 3/5*(ControlPannel_Width-2*Side_Border);
PanelHeight_WorkSpace_1 = PanelBorder_top + PanelBorder_bottom + round(2*Panel_Line_Height);
Shift_WorkSpace_1 = 2/5*(ControlPannel_Width-2*Side_Border);

PanelWidth_WorkSpace_2 = floor(2/3*(ControlPannel_Width-2*Side_Border-InterPanelDistance_Width));
PanelHeight_WorkSpace_2 = PanelBorder_top + PanelBorder_bottom + round(7*Panel_Line_Height);

PanelWidth_WorkSpace_3 = floor(1/3*(ControlPannel_Width-2*Side_Border-InterPanelDistance_Width));
PanelHeight_WorkSpace_3 = PanelBorder_top + PanelBorder_bottom + round(7*Panel_Line_Height);

PanelWidth_WorkSpace_4 = ControlPannel_Width-2*Side_Border;
PanelHeight_WorkSpace_4 = PanelBorder_top + PanelBorder_bottom + round(4*Panel_Line_Height);

PanelWidth_WorkSpace_5 = ControlPannel_Width-2*Side_Border;
PanelHeight_WorkSpace_5 = PanelBorder_top + PanelBorder_bottom + round(5*Panel_Line_Height);

PanelWidth_WorkSpace_6 = ControlPannel_Width-2*Side_Border;
PanelHeight_WorkSpace_6 = PanelBorder_top + PanelBorder_bottom + round(4*Panel_Line_Height);

IntraPanelDistance_Pannel1a = floor((PanelWidth_WorkSpace_1-2*(TextSize_Pannel1(1)+EditSize(1)))/5);
IntraPanelDistance_Pannel1b = floor((PanelWidth_WorkSpace_1-PushButtonSize_Pannel1(1))/2);
IntraPanelDistance_Pannel2 = floor((PanelWidth_WorkSpace_2-EditSize(1)-TextSize_Pannel2(1))/3);
IntraPanelDistance_Pannel4 = floor((PanelWidth_WorkSpace_4-2*(TextSize_Pannel4(1)+EditSize(1)))/5);
IntraPanelDistance_Pannel5 = floor((PanelWidth_WorkSpace_5-SliderSize_Pannel5(1)-EditSize(1)-TextSize_Pannel5(1))/5);
IntraPanelDistance_Pannel6a = floor((PanelWidth_WorkSpace_6-EditSize(1)-TextSize_Pannel6_small(1)-2*PushButtonSize_Pannel6_small(1))/7);
IntraPanelDistance_Pannel6b = floor((PanelWidth_WorkSpace_6-EditSize(1)-TextSize_Pannel6_long(1)-PushButtonSize_Pannel6_long(1))/4);

set(h.sptPALM_ControlPannel,'DefaultUicontrolFontSize',FontSize);
set(h.sptPALM_ControlPannel,'DefaultUicontrolUnits','Pixels');
set(h.sptPALM_ControlPannel,'DefaultUipanelFontSize',FontSize);
set(h.sptPALM_ControlPannel,'DefaultUipanelUnits','Pixels');

%% Definition of the path leading to the data
%% ==========================================

Position_Width = Side_Border;
Position_Height = ControlPannel_Height-Height_Border-TextFolderName(2);
h.FolderPath_Text = uicontrol(h.sptPALM_ControlPannel,'Style','text',...
    'String','Directory name',...
    'HorizontalAlignment','center',...
    'Position',[Position_Width Position_Height TextFolderName]);


%% Definition of the pannels
%% =========================

Panel_StartPosition = [Side_Border+Shift_WorkSpace_1/2 ControlPannel_Height-Height_Border-TextFolderName(2)-InterPanelDistance_Height-PanelHeight_WorkSpace_1];
Panel_Size = [PanelWidth_WorkSpace_1 PanelHeight_WorkSpace_1];

h.Panel_LoadingTracks = uipanel(h.sptPALM_ControlPannel, 'Title', 'Loading MTT data',...
    'Position', [Panel_StartPosition Panel_Size], 'FontWeight', 'bold');

Panel_StartPosition = [Side_Border ControlPannel_Height-Height_Border-TextFolderName(2)-2*InterPanelDistance_Height-PanelHeight_WorkSpace_1-PanelHeight_WorkSpace_2];
Panel_Size = [PanelWidth_WorkSpace_2 PanelHeight_WorkSpace_2];

h.Panel_Analysis_Parameters = uipanel(h.sptPALM_ControlPannel, 'Title', 'Analysis parameters',...
    'Position', [Panel_StartPosition Panel_Size], 'FontWeight', 'bold');

Panel_StartPosition = [Side_Border+PanelWidth_WorkSpace_2+InterPanelDistance_Width, ...
    ControlPannel_Height-Height_Border-TextFolderName(2)-2*InterPanelDistance_Height-PanelHeight_WorkSpace_1-PanelHeight_WorkSpace_2];
Panel_Size = [PanelWidth_WorkSpace_3 PanelHeight_WorkSpace_3];

h.Panel_Action = uipanel(h.sptPALM_ControlPannel, 'Title', 'MSD & Diffusion analysis',...
    'Position', [Panel_StartPosition Panel_Size], 'FontWeight', 'bold');

Panel_StartPosition = [Side_Border ControlPannel_Height-Height_Border-TextFolderName(2)-3*InterPanelDistance_Height-PanelHeight_WorkSpace_1-PanelHeight_WorkSpace_2-PanelHeight_WorkSpace_4];
Panel_Size = [PanelWidth_WorkSpace_4 PanelHeight_WorkSpace_4];

h.Panel_Results = uipanel(h.sptPALM_ControlPannel, 'Title', 'Statistics',...
    'Position', [Panel_StartPosition Panel_Size], 'FontWeight', 'bold');

Panel_StartPosition = [Side_Border, ...
    ControlPannel_Height-Height_Border-TextFolderName(2)-4*InterPanelDistance_Height-PanelHeight_WorkSpace_1-PanelHeight_WorkSpace_2-PanelHeight_WorkSpace_4-PanelHeight_WorkSpace_5];
Panel_Size = [PanelWidth_WorkSpace_5 PanelHeight_WorkSpace_5];

h.Panel_Visualization = uipanel(h.sptPALM_ControlPannel, 'Title', 'Visualization tool',...
    'Position', [Panel_StartPosition Panel_Size], 'FontWeight', 'bold');

Panel_StartPosition = [Side_Border, ...
    ControlPannel_Height-Height_Border-TextFolderName(2)-5*InterPanelDistance_Height-PanelHeight_WorkSpace_1-PanelHeight_WorkSpace_2-PanelHeight_WorkSpace_4-PanelHeight_WorkSpace_5-PanelHeight_WorkSpace_6];
Panel_Size = [PanelWidth_WorkSpace_6 PanelHeight_WorkSpace_6];

h.Panel_Simulation = uipanel(h.sptPALM_ControlPannel, 'Title', 'Simulation of sptPALM experiments',...
    'Position', [Panel_StartPosition Panel_Size], 'FontWeight', 'bold');


%% Elements defining the loading MTT data parameters (Pannel 1)
%% ===========================================================

Position_Width = [IntraPanelDistance_Pannel1a, 2*IntraPanelDistance_Pannel1a+TextSize_Pannel1(1), 3*IntraPanelDistance_Pannel1a+EditSize(1)+TextSize_Pannel1(1), ...
    4*IntraPanelDistance_Pannel1a+EditSize(1)+2*TextSize_Pannel1(1)];
Position_Height = [PanelHeight_WorkSpace_1-PanelBorder_top-Panel_Line_Height, PanelHeight_WorkSpace_1-PanelBorder_top-2*Panel_Line_Height, ...
    PanelHeight_WorkSpace_1-PanelBorder_top-3*Panel_Line_Height];

% line 1

uicontrol(h.Panel_LoadingTracks,'Style','text',...
    'String','Acquisition time (ms)',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(1) Position_Height(1) TextSize_Pannel1]);

h.AcquisitionTime = uicontrol(h.Panel_LoadingTracks, 'Style', 'edit',...
    'String', '20',...
    'Position', [Position_Width(2) Position_Height(1) EditSize]);

uicontrol(h.Panel_LoadingTracks,'Style','text',...
    'String','Pixel size (µm)',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(3) Position_Height(1) TextSize_Pannel1]);

h.PixelSize = uicontrol(h.Panel_LoadingTracks, 'Style', 'edit',...
    'String', '0.102',...
    'Position', [Position_Width(4) Position_Height(1) EditSize]);


% line 2

Position_Width = IntraPanelDistance_Pannel1b;

h.LoadMTT = uicontrol(h.Panel_LoadingTracks, 'Style', 'pushbutton',...
    'String', 'Load MTT files',...
    'Position', [Position_Width(1) Position_Height(2) PushButtonSize_Pannel1], 'FontWeight', 'bold');


%% Elements defining the analysis parameters (Pannel 2)
%% ===================================================

Position_Width = [IntraPanelDistance_Pannel2 2*IntraPanelDistance_Pannel2+EditSize(1)];
Position_Height = [PanelHeight_WorkSpace_2-PanelBorder_top-Panel_Line_Height, PanelHeight_WorkSpace_2-PanelBorder_top-2*Panel_Line_Height, ...
    PanelHeight_WorkSpace_2-PanelBorder_top-3*Panel_Line_Height, PanelHeight_WorkSpace_2-PanelBorder_top-4*Panel_Line_Height, ...
    PanelHeight_WorkSpace_2-PanelBorder_top-5*Panel_Line_Height, PanelHeight_WorkSpace_2-PanelBorder_top-6*Panel_Line_Height, ...
    PanelHeight_WorkSpace_2-PanelBorder_top-7*Panel_Line_Height] ;

% line1

h.MaxStepLength = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
    'String', '',...
    'Position', [Position_Width(1) Position_Height(1) EditSize]);

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Maximum distance between two detections (µm)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(1) TextSize_Pannel2]);

% line2

h.MaxBlinks = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
    'String', '3',...
    'Position', [Position_Width(1) Position_Height(2) EditSize]);

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Maximum number of blinks (frames)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(2) TextSize_Pannel2]);

% line3

h.MinTrajLength = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
    'String', '5',...
    'Position', [Position_Width(1) Position_Height(3) EditSize]);

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Minimum trajectory duration (frames)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(3) TextSize_Pannel2]);

% line4

h.MinNumberPoints = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
    'String', '0.75',...
    'Position', [Position_Width(1) Position_Height(4) EditSize]);

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Minimum number of points (%)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(4) TextSize_Pannel2]);

% line5

h.MinimumNumberPointsMSD = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
    'String', '3',...
    'Position', [Position_Width(1) Position_Height(5) EditSize]);

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Minimum number of points for MSD estimation',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(5) TextSize_Pannel2]);

% line6

h.NumberPointsMSDFit = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
    'String', '4',...
    'Position', [Position_Width(1) Position_Height(6) EditSize]);

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Number of points used for Dapp estimation',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(6) TextSize_Pannel2]);

% line7

h.MaxDisplayTime = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
    'String', '0.5',...
    'Position', [Position_Width(1) Position_Height(7) EditSize]);

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Maximum display time for MSD (s)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(7) TextSize_Pannel2]);


%% Elements defining the action pannel (Pannel 3)
%% =============================================

Position_Width = [round((PanelWidth_WorkSpace_3-PushButtonSize_Pannel3)/2), round((PanelWidth_WorkSpace_3-PushButtonSize_Pannel3)/2)+EditSize(1)];
Position_Height = [PanelHeight_WorkSpace_3-PanelBorder_top-Panel_Line_Height, PanelHeight_WorkSpace_3-PanelBorder_top-2*Panel_Line_Height, ...
    PanelHeight_WorkSpace_3-PanelBorder_top-3*Panel_Line_Height, PanelHeight_WorkSpace_3-PanelBorder_top-4*Panel_Line_Height, ...
    PanelHeight_WorkSpace_3-PanelBorder_top-5*Panel_Line_Height, PanelHeight_WorkSpace_3-PanelBorder_top-6*Panel_Line_Height, ...
    PanelHeight_WorkSpace_3-PanelBorder_top-7*Panel_Line_Height] ;


h.AnalyseTrajectories = uicontrol(h.Panel_Action, 'Style', 'pushbutton',...
    'String', 'Analyse trajectories',...
    'Position', [Position_Width(1) Position_Height(2) PushButtonSize_Pannel3]);

h.DiffusionCalculationMethod = uicontrol(h.Panel_Action, 'Style', 'popupmenu',...
    'String', {'Average of MSD', 'Fit of MSD'},...
    'Position', [Position_Width(1) Position_Height(3) PopupmenuSize]);

h.SaveForTesseler = uicontrol(h.Panel_Action, 'Style', 'pushbutton',...
    'String', 'Save data for Tesseler',...
    'Position', [Position_Width(1) Position_Height(5) PushButtonSize_Pannel3]);

h.PlotPreviousAnalysis = uicontrol(h.Panel_Action, 'Style', 'pushbutton',...
    'String', 'Plot previous analysis',...
    'Position', [Position_Width(1) Position_Height(6) PushButtonSize_Pannel3]);

h.DataTypePlot = uicontrol(h.Panel_Action, 'Style', 'popupmenu',...
    'String', {'D distribution', 'MSD curve', 'Trajectories plot (all)', 'Trajectories plot (populations)'},...
    'Position', [Position_Width(1) Position_Height(7) PopupmenuSize]);


%% Elements defining the results of the analysis (Pannel 4)
%% ========================================================

Position_Width = [IntraPanelDistance_Pannel4 2*IntraPanelDistance_Pannel4+TextSize_Pannel4(1), ...
    3*IntraPanelDistance_Pannel4+TextSize_Pannel4(1)+EditSize(1), 4*IntraPanelDistance_Pannel4+2*TextSize_Pannel4(1)+EditSize(1) ];
Position_Height = [PanelHeight_WorkSpace_4-PanelBorder_top-Panel_Line_Height, PanelHeight_WorkSpace_4-PanelBorder_top-2*Panel_Line_Height, ...
    PanelHeight_WorkSpace_4-PanelBorder_top-3*Panel_Line_Height, PanelHeight_WorkSpace_4-PanelBorder_top-4*Panel_Line_Height];

% line1

uicontrol(h.Panel_Results, 'Style', 'text',...
    'String', 'Number of movies loaded',...
    'HorizontalAlignment', 'right',...
    'Position', [Position_Width(1) Position_Height(1) TextSize_Pannel4]);

h.NMovies = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(2) Position_Height(1) EditSize]);

uicontrol(h.Panel_Results,'Style','text',...
    'String','Number of trajectories loaded',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(3) Position_Height(1) TextSize_Pannel4]);

h.NTrajectories = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(4) Position_Height(1) EditSize]);

% line2

uicontrol(h.Panel_Results,'Style','text',...
    'String','Number of trajectories after filtering',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(1) Position_Height(2) TextSize_Pannel4]);

h.NTrajectoriesFiltered = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(2) Position_Height(2) EditSize]);

uicontrol(h.Panel_Results,'Style','text',...
    'String','Number of trajectories found in ROI',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(3) Position_Height(2) TextSize_Pannel4]);

h.NTrajectoriesROI = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(4) Position_Height(2) EditSize]);

% line3

uicontrol(h.Panel_Results,'Style','text',...
    'String','Number of trajectories used for MSD',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(1) Position_Height(3) TextSize_Pannel4]);

h.NTrajectoriesMSD = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(2) Position_Height(3) EditSize]);

uicontrol(h.Panel_Results,'Style','text',...
    'String','Number of trajectories used for Diff',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(3) Position_Height(3) TextSize_Pannel4]);

h.NTrajectoriesDiff = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(4) Position_Height(3) EditSize]);

% line4

uicontrol(h.Panel_Results,'Style','text',...
    'String','Density of tracks in ROI (/µm²)',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(1) Position_Height(4) TextSize_Pannel4]);

h.TrackDensity = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(2) Position_Height(4) EditSize]);


%% Elements defining the results of the analysis (Pannel 5)
%% ========================================================

Position_Height = [PanelHeight_WorkSpace_5-PanelBorder_top-Panel_Line_Height, PanelHeight_WorkSpace_5-PanelBorder_top-2*Panel_Line_Height, ...
    PanelHeight_WorkSpace_5-PanelBorder_top-3*Panel_Line_Height, PanelHeight_WorkSpace_5-PanelBorder_top-4*Panel_Line_Height, ...
    PanelHeight_WorkSpace_5-PanelBorder_top-5*Panel_Line_Height];

% line1

Position_Width = [IntraPanelDistance_Pannel5 2*IntraPanelDistance_Pannel5+PushButtonSize_Pannel5(1), ...
    3*IntraPanelDistance_Pannel5+2*PushButtonSize_Pannel5(1), 4*IntraPanelDistance_Pannel5+TextSize_Pannel5(1)+2*PushButtonSize_Pannel5(1)];

h.LoadMovie = uicontrol(h.Panel_Visualization, 'Style', 'pushbutton',...
    'String', 'Load movie',...
    'Position', [Position_Width(1) Position_Height(1) PushButtonSize_Pannel5]);

h.LoadTraj = uicontrol(h.Panel_Visualization, 'Style', 'pushbutton',...
    'String', 'Load trajectories',...
    'Position', [Position_Width(2) Position_Height(1) PushButtonSize_Pannel5]);

uicontrol(h.Panel_Visualization,'Style','text',...
    'String','Minimum track length',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(3) Position_Height(1) TextSize_Pannel5]);

h.MinTrackLength = uicontrol(h.Panel_Visualization, 'Style', 'edit',...
    'String', '1',...
    'Position', [Position_Width(4) Position_Height(1) EditSize]);

% line2

Position_Width = [IntraPanelDistance_Pannel5 2*IntraPanelDistance_Pannel5+PushButtonSize_Pannel5(1)];

h.CreateROI = uicontrol(h.Panel_Visualization, 'Style', 'pushbutton',...
    'String', 'Create ROI',...
    'Position', [Position_Width(1) Position_Height(2) PushButtonSize_Pannel5]);

h.DeleteROI = uicontrol(h.Panel_Visualization, 'Style', 'pushbutton',...
    'String', 'Delete ROI',...
    'Position', [Position_Width(2) Position_Height(2) PushButtonSize_Pannel5]);

% line3

Position_Width = [IntraPanelDistance_Pannel5 2*IntraPanelDistance_Pannel5+TextSize_Pannel5(1), ...
   3*IntraPanelDistance_Pannel5+TextSize_Pannel5(1)+SliderSize_Pannel5(1)];

uicontrol(h.Panel_Visualization,'Style','text',...
    'String','Select frame ',...
    'HorizontalAlignment','center',...
    'Position',[Position_Width(1) Position_Height(3) TextSize_Pannel5]);

h.Slider_SelectFrame = uicontrol(h.Panel_Visualization,'Style','slider',...
    'Min', 1, 'Max', 10, 'Value', 1,...
    'Position',[Position_Width(2) Position_Height(3) SliderSize_Pannel5],...
    'SliderStep', [1/10,1/10],...
    'Visible', 'on');

h.Edit_SelectFrame = uicontrol(h.Panel_Visualization, 'Style', 'edit',...
    'String', '1',...
    'Position', [Position_Width(3) Position_Height(3) EditSize]);

% line4

Position_Width = [IntraPanelDistance_Pannel5 2*IntraPanelDistance_Pannel5+TextSize_Pannel5(1), ...
   3*IntraPanelDistance_Pannel5+TextSize_Pannel5(1)+SliderSize_Pannel5(1)];

uicontrol(h.Panel_Visualization,'Style','text',...
    'String','Contrast (upper limit) ',...
    'HorizontalAlignment','center',...
    'Position',[Position_Width(1) Position_Height(4) TextSize_Pannel5]);

h.Slider_UpperContrast = uicontrol(h.Panel_Visualization,'Style','slider',...
    'Min', 1, 'Max', 10, 'Value', 1,...
    'Position',[Position_Width(2) Position_Height(4) SliderSize_Pannel5],...
    'SliderStep', [1/10,1/10],...
    'Visible', 'on');

h.Edit_UpperContrast = uicontrol(h.Panel_Visualization, 'Style', 'edit',...
    'String', '1',...
    'Position', [Position_Width(3) Position_Height(4) EditSize]);

% line5

Position_Width = [IntraPanelDistance_Pannel5 2*IntraPanelDistance_Pannel5+TextSize_Pannel5(1), ...
   3*IntraPanelDistance_Pannel5+TextSize_Pannel5(1)+SliderSize_Pannel5(1)];

uicontrol(h.Panel_Visualization,'Style','text',...
    'String','Contrast (lower limit) ',...
    'HorizontalAlignment','center',...
    'Position',[Position_Width(1) Position_Height(5) TextSize_Pannel5]);

h.Slider_LowerContrast = uicontrol(h.Panel_Visualization,'Style','slider',...
    'Min', 1, 'Max', 10, 'Value', 1,...
    'Position',[Position_Width(2) Position_Height(5) SliderSize_Pannel5],...
    'SliderStep', [1/10,1/10],...
    'Visible', 'on');

h.Edit_LowerContrast = uicontrol(h.Panel_Visualization, 'Style', 'edit',...
    'String', '1',...
    'Position', [Position_Width(3) Position_Height(5) EditSize]);


%% Elements defining the parameters for the simulation of diffusion (Pannel 6)
%% ===========================================================================

Position_Height = [PanelHeight_WorkSpace_6-PanelBorder_top-Panel_Line_Height, PanelHeight_WorkSpace_6-PanelBorder_top-2*Panel_Line_Height, ...
    PanelHeight_WorkSpace_6-PanelBorder_top-3*Panel_Line_Height, PanelHeight_WorkSpace_6-PanelBorder_top-4*Panel_Line_Height];

% line1

Position_Width = [IntraPanelDistance_Pannel6a 2*IntraPanelDistance_Pannel6a+EditSize(1), ...
    3*IntraPanelDistance_Pannel6a+EditSize(1)+TextSize_Pannel6_small(1), 4*IntraPanelDistance_Pannel6a+2*EditSize(1)+TextSize_Pannel6_small(1), ...
    5*IntraPanelDistance_Pannel6a+2*EditSize(1)+2*TextSize_Pannel6_small(1), 6*IntraPanelDistance_Pannel6a+3*EditSize(1)+2*TextSize_Pannel6_small(1)];

h.Simulation_Diff1 = uicontrol(h.Panel_Simulation, 'Style', 'edit',...
    'String', '',...
    'Position', [Position_Width(1) Position_Height(1) EditSize]);

uicontrol(h.Panel_Simulation,'Style','text',...
    'String','Diffusion coeff #1',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(1) TextSize_Pannel6_small]);

h.Simulation_Diff2 = uicontrol(h.Panel_Simulation, 'Style', 'edit',...
    'String', '',...
    'Position', [Position_Width(3) Position_Height(1) EditSize]);

uicontrol(h.Panel_Simulation,'Style','text',...
    'String','Diffusion coeff #2',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(4) Position_Height(1) TextSize_Pannel6_small]);

h.Simulation_Fraction = uicontrol(h.Panel_Simulation, 'Style', 'edit',...
    'String', '',...
    'Position', [Position_Width(5) Position_Height(1) EditSize]);

uicontrol(h.Panel_Simulation,'Style','text',...
    'String','Fraction of prot1 (%)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(6) Position_Height(1) TextSize_Pannel6_long]);

% line2

Position_Width = [IntraPanelDistance_Pannel6a 2*IntraPanelDistance_Pannel6a+EditSize(1), ...
    3*IntraPanelDistance_Pannel6a+EditSize(1)+TextSize_Pannel6_small(1), 4*IntraPanelDistance_Pannel6a+EditSize(1)+TextSize_Pannel6_small(1)+PushButtonSize_Pannel6_small(1)];

h.Simulation_NFrames = uicontrol(h.Panel_Simulation, 'Style', 'edit',...
    'String', '1000',...
    'Position', [Position_Width(1) Position_Height(2) EditSize]);

uicontrol(h.Panel_Simulation,'Style','text',...
    'String','Number of frames',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(2) TextSize_Pannel6_small]);

h.Simulation_EmissionParameters = uicontrol(h.Panel_Simulation, 'Style', 'pushbutton',...
    'String', 'Change emission parameters',...
    'Position', [Position_Width(3) Position_Height(2) PushButtonSize_Pannel6_small]);

h.Simulation_AquisitionParameters = uicontrol(h.Panel_Simulation, 'Style', 'pushbutton',...
    'String', 'Change aquisition parameters',...
    'Position', [Position_Width(4) Position_Height(2) PushButtonSize_Pannel6_small]);

% line3

Position_Width = [IntraPanelDistance_Pannel6b, 2*IntraPanelDistance_Pannel6b+PushButtonSize_Pannel6_long(1), ...
    3*IntraPanelDistance_Pannel6b+PushButtonSize_Pannel6_long(1)+CheckBoxSize(1)];

h.LaunchSimulation = uicontrol(h.Panel_Simulation, 'Style', 'pushbutton',...
    'String', 'Lauch simulation',...
    'Position', [Position_Width(1) Position_Height(4) PushButtonSize_Pannel6_long]);

h.Simulation_Verbose = uicontrol(h.Panel_Simulation, 'Style', 'checkbox',...
    'Value', 1,...
    'Position', [Position_Width(2) Position_Height(4) CheckBoxSize]);

uicontrol(h.Panel_Simulation,'Style','text',...
    'String','Display all images',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(3) Position_Height(4) TextSize_Pannel6_long]);

end