%*****************************
%
% sptPALM_components.m
%
% ****************************
%
% JB Fiche
% Creation : 2014
% Last update : 2020/05/26
%
% fiche@cbs.cnrs.fr
% -------------------------------------------------------------------------
% Purpose: This function is used to create the front Panel of
% sptPALM_viewer app.
% -------------------------------------------------------------------------
% Specific:
% -------------------------------------------------------------------------
% To fix:
% -------------------------------------------------------------------------
% Copyright Centre National de la Recherche Scientifique, 2020.

function h = sptPALM_components(h, ScreenOption, Side_Border, Height_Border, ControlPanel_Width, ControlPanel_Height)

%% General parameters
%% ==================

switch ScreenOption
    case 'large'
        FontSize = 8;
        PanelBorder_top = 15;
        PanelBorder_bottom = 5;
        InterPanelDistance_Height = 10;
        InterPanelDistance_Width = 10;
        
        Text_height = 15;
        Edit_height = 20;
        Edit_height_large = 30;
        PushButton_height = 27;
        PushButton_height_large = 30;
        CheckBox_height = 20;
        Slider_height = 20;
        Popupmenu_height = 25;
        
    case 'small'
        FontSize = 7;
        PanelBorder_top = 15;
        PanelBorder_bottom = 5;
        InterPanelDistance_Height = 7;
        InterPanelDistance_Width = 7;
        
        Text_height = 13;
        Edit_height = 17;
        Edit_height_large = 25;
        PushButton_height = 17;
        PushButton_height_large = 25;
        CheckBox_height = 17;
        Slider_height = 17;
        Popupmenu_height = 20;
end

Total_lines = 27;
Total_Panels = 5;

set(h.sptPALM_ControlPanel,'DefaultUicontrolFontSize',FontSize);
set(h.sptPALM_ControlPanel,'DefaultUicontrolUnits','Pixels');
set(h.sptPALM_ControlPanel,'DefaultUipanelFontSize',FontSize);
set(h.sptPALM_ControlPanel,'DefaultUipanelUnits','Pixels');

%% Text window : indication of the working folder path
%% ===================================================

TextSize_FolderName = [ControlPanel_Width - 2*Side_Border, 30];
Position_Width = Side_Border;
Position_Height = ControlPanel_Height-Height_Border-TextSize_FolderName(2);
h.FolderPath_Text = uicontrol(h.sptPALM_ControlPanel,'Style','text',...
    'String','Directory name',...
    'HorizontalAlignment','center',...
    'Position',[Position_Width Position_Height TextSize_FolderName]);

%% Panel 1 : Define the acquisition parameters (acquisition time and pixel
%% size) and load the MTT .mat files.
%% ==================================

% According to the size of the window, define the spacing between two lines.

Panel_Line_Height = round( 1/Total_lines * (ControlPanel_Height - 2*Height_Border - ...
    Total_Panels * (InterPanelDistance_Height + PanelBorder_top + PanelBorder_bottom) - ...
    TextSize_FolderName(2)));

% Define the Panel

NLines_Panel_1 = 5;
PanelWidth_1 = ControlPanel_Width - 2*Side_Border;
PanelHeight_1 = PanelBorder_top + PanelBorder_bottom + round(NLines_Panel_1*Panel_Line_Height);

Panel_StartPosition = [Side_Border, ...
    ControlPanel_Height - ...
    Height_Border - ...
    TextSize_FolderName(2) - ...
    InterPanelDistance_Height - ...
    PanelHeight_1];
Panel_Size = [PanelWidth_1 PanelHeight_1];

h.Panel_LoadingTracks = uipanel(h.sptPALM_ControlPanel, 'Title', 'Load tracking data',...
    'Position', [Panel_StartPosition Panel_Size], 'FontWeight', 'bold');

% Define the size of the objects that are in the Panel

TextSize_1 = [130, Text_height];
EditSize_1 = [45, Edit_height];

EditSize_2 = [130, Edit_height_large];
CheckBoxSize = [15, CheckBox_height];
PopupmenuSize = [120, Popupmenu_height];
TextSize_2 = [110, Text_height];

TextSize_3 = [120, Text_height];
EditSize_3 = [250, Edit_height_large];
PushButtonSize = [150, PushButton_height_large];

% Define the position of the objects in the Panel

Width_Separation_Line1 = floor((PanelWidth_1 - 2*(TextSize_1(1) + EditSize_1(1)))/2);
Width_Separation_Line2 = floor((PanelWidth_1 - PopupmenuSize(1) - ...
    TextSize_2(1) - CheckBoxSize(1) - PushButtonSize(1) - EditSize_2(1))/4);
Width_Separation_Line3 = floor((PanelWidth_1 - EditSize_3(1) - TextSize_3(1) - PushButtonSize(1))/3);

Position_Height = [PanelHeight_1-PanelBorder_top-Panel_Line_Height, ...
    PanelHeight_1-PanelBorder_top-2.75*Panel_Line_Height, ...
    PanelHeight_1-PanelBorder_top-4.5*Panel_Line_Height];

% line 1

Position_Width = [Width_Separation_Line1, ...
    Width_Separation_Line1 + TextSize_1(1),...
    Width_Separation_Line1+EditSize_1(1)+TextSize_1(1), ...
    Width_Separation_Line1+EditSize_1(1)+2*TextSize_1(1)];

uicontrol(h.Panel_LoadingTracks,'Style','text',...
    'String','Acquisition time (ms)',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(1) Position_Height(1) TextSize_1]);

h.AcquisitionTime = uicontrol(h.Panel_LoadingTracks, 'Style', 'edit',...
    'String', '20',...
    'Position', [Position_Width(2) Position_Height(1) EditSize_1]);

uicontrol(h.Panel_LoadingTracks,'Style','text',...
    'String','Pixel size (um)',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(3) Position_Height(1) TextSize_1]);

h.PixelSize = uicontrol(h.Panel_LoadingTracks, 'Style', 'edit',...
    'String', '0.102',...
    'Position', [Position_Width(4) Position_Height(1) EditSize_1]);

% line 2

Position_Width = [Width_Separation_Line2, ...
    2*Width_Separation_Line2 + PopupmenuSize(1),...
    2*Width_Separation_Line2 + PopupmenuSize(1) + EditSize_2(1), ...
    3*Width_Separation_Line2 + PopupmenuSize(1) + EditSize_2(1) + PushButtonSize(1), ...
    3*Width_Separation_Line2 + PopupmenuSize(1) + EditSize_2(1) + PushButtonSize(1) + TextSize_2(1), ...
    ];

h.TrackingSoftware = uicontrol(h.Panel_LoadingTracks, 'Style', 'popupmenu',...
    'String', {'MTT', 'TrackMate'}, 'FontWeight', 'bold', ...
    'Position', [Position_Width(1) Position_Height(2) PopupmenuSize]);

h.MTT_FileName = uicontrol(h.Panel_LoadingTracks, 'Style', 'edit',...
    'String', '*.mat', ...
    'Position', [Position_Width(2) Position_Height(2) EditSize_2]);

h.LoadMTT = uicontrol(h.Panel_LoadingTracks, 'Style', 'pushbutton',...
    'String', 'Load MTT files',...
    'Position', [Position_Width(3) Position_Height(2) PushButtonSize], 'FontWeight', 'bold');

uicontrol(h.Panel_LoadingTracks,'Style','text',...
    'String','Save localizations?',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(4) Position_Height(2) TextSize_2]);

h.Save_traj_txt = uicontrol(h.Panel_LoadingTracks, 'Style', 'checkbox',...
    'Value', 0,...
    'Position', [Position_Width(5) Position_Height(2) CheckBoxSize]);

% line 3

Position_Width = [Width_Separation_Line3, ...
    Width_Separation_Line3 + TextSize_3(1), ...
    2*Width_Separation_Line3 + TextSize_3(1) + EditSize_3(1)];

uicontrol(h.Panel_LoadingTracks,'Style','text',...
    'String','Results file name',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(1) Position_Height(3) TextSize_3]);

h.Saving_file_name = uicontrol(h.Panel_LoadingTracks, 'Style', 'edit',...
    'String', 'MTT_sptPALM_analysis.mat',...
    'Position', [Position_Width(2) Position_Height(3) EditSize_3]);

h.Load_Previous_analysis = uicontrol(h.Panel_LoadingTracks, 'Style', 'pushbutton',...
    'String', 'Load previous analysis',...
    'Position', [Position_Width(3) Position_Height(3) PushButtonSize], 'FontWeight', 'bold');

%% Panel 2 : Define the parameters for the analysis
%% =================================================

% Define the panel

NLines_Panel_2 = 7;
PanelWidth_2 = floor(2/3*(ControlPanel_Width - 2*Side_Border - InterPanelDistance_Width));
PanelHeight_2 = PanelBorder_top + PanelBorder_bottom + round(NLines_Panel_2*Panel_Line_Height);

Panel_StartPosition = [Side_Border, ...
    ControlPanel_Height-Height_Border - ...
    TextSize_FolderName(2) - ...
    2*InterPanelDistance_Height - ...
    PanelHeight_1 - ...
    PanelHeight_2];
Panel_Size = [PanelWidth_2 PanelHeight_2];

h.Panel_Analysis_Parameters = uipanel(h.sptPALM_ControlPanel, 'Title', 'Analysis parameters',...
    'Position', [Panel_StartPosition Panel_Size], 'FontWeight', 'bold');


% Define the size of the objects that are in the Panel

EditSize = [45, Edit_height];
TextSize = [300 Text_height];
PopupmenuSize = [150, Popupmenu_height];

% Define the position of the objects in the Panel

Width_Separation = floor((PanelWidth_2-EditSize(1)-TextSize(1))/3);

Position_Width = [Width_Separation 2*Width_Separation+EditSize(1)];
Position_Height = [PanelHeight_2-PanelBorder_top-Panel_Line_Height, ...
    PanelHeight_2-PanelBorder_top-2*Panel_Line_Height, ...
    PanelHeight_2-PanelBorder_top-3*Panel_Line_Height, ...
    PanelHeight_2-PanelBorder_top-4*Panel_Line_Height, ...
    PanelHeight_2-PanelBorder_top-5*Panel_Line_Height, ...
    PanelHeight_2-PanelBorder_top-6*Panel_Line_Height, ...
    PanelHeight_2-PanelBorder_top-7*Panel_Line_Height] ;

% line1

h.MaxStepLength = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
    'String', '',...
    'Position', [Position_Width(1) Position_Height(1) EditSize]);

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Maximum distance between two detections (um)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(1) TextSize]);

% line2

h.MaxBlinks = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
    'String', '3',...
    'Position', [Position_Width(1) Position_Height(2) EditSize]);

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Maximum duration for the blinking (frames)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(2) TextSize]);

% line3

h.MinTrajLength = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
    'String', '7',...
    'Position', [Position_Width(1) Position_Height(3) EditSize]);

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Minimum trajectory duration (frames)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(3) TextSize]);

% % line4
% 
% h.MinNumberPoints = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
%     'String', '0.75',...
%     'Position', [Position_Width(1) Position_Height(4) EditSize]);
% 
% uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
%     'String','Minimum number of points (%)',...
%     'HorizontalAlignment','left',...
%     'Position',[Position_Width(2) Position_Height(4) TextSize]);
% 
% % line5
% 
% h.MinimumNumberPointsMSD = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
%     'String', '3',...
%     'Position', [Position_Width(1) Position_Height(5) EditSize]);
% 
% uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
%     'String','Minimum number of points for MSD estimation',...
%     'HorizontalAlignment','left',...
%     'Position',[Position_Width(2) Position_Height(5) TextSize]);

% line4

h.NumberPointsMSDFit = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
    'String', '4',...
    'Position', [Position_Width(1) Position_Height(4) EditSize]);

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Number of points used for Dint fit',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(4) TextSize]);

% line5

h.MaxDisplayTime = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'edit',...
    'String', '0.5',...
    'Position', [Position_Width(1) Position_Height(5) EditSize]);

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Maximum display time for MSD (s)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(5) TextSize]);

% line6&7

uicontrol(h.Panel_Analysis_Parameters,'Style','text',...
    'String','Method for the calculation of D :',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(1) Position_Height(6) TextSize]);

h.DiffusionCalculationMethod = uicontrol(h.Panel_Analysis_Parameters, 'Style', 'popupmenu',...
    'String', {'Average of MSD', 'Fit of MSD'},...
    'Position', [Position_Width(1) Position_Height(7) PopupmenuSize]);


%% Panel 3 : Launch the analysis
%% =============================

% Define the Panel

NLines_Panel_3 = 7;
PanelWidth_3 = floor(1/3*(ControlPanel_Width - 2*Side_Border - InterPanelDistance_Width));
PanelHeight_3 = PanelBorder_top + PanelBorder_bottom + round(NLines_Panel_3*Panel_Line_Height);

Panel_StartPosition = [Side_Border+PanelWidth_2+InterPanelDistance_Width, ...
    ControlPanel_Height-Height_Border - ...
    TextSize_FolderName(2) - ...
    2*InterPanelDistance_Height - ...
    PanelHeight_1 - ...
    PanelHeight_2];
Panel_Size = [PanelWidth_3 PanelHeight_3];
h.Panel_Action = uipanel(h.sptPALM_ControlPanel, 'Title', 'Diffusion analysis',...
    'Position', [Panel_StartPosition Panel_Size], 'FontWeight', 'bold');

% Define the size of the objects that are in the Panel

PushButtonSize = [150,PushButton_height_large];
TextSize = [130, Text_height];
CheckBoxSize = [15, CheckBox_height];

% Define the position of the objects in the Panel

Position_Width = round((PanelWidth_3-PushButtonSize(1))/2);
Position_Width_checkbox = [ round((PanelWidth_3-TextSize(1)-CheckBoxSize(1))/2), ...
    round((PanelWidth_3-TextSize(1)-CheckBoxSize(1))/2) + CheckBoxSize(1)];
Position_Height = [PanelHeight_3-PanelBorder_top-1.5*Panel_Line_Height, ...
    PanelHeight_3-PanelBorder_top-2.5*Panel_Line_Height, ...
    PanelHeight_3-PanelBorder_top-3.5*Panel_Line_Height, ...
    PanelHeight_3-PanelBorder_top-4*Panel_Line_Height, ...
    PanelHeight_3-PanelBorder_top-5*Panel_Line_Height, ...
    PanelHeight_3-PanelBorder_top-6*Panel_Line_Height, ...
    PanelHeight_3-PanelBorder_top-7*Panel_Line_Height] ;

% Position of all the objects

h.AnalyseTrajectories = uicontrol(h.Panel_Action, 'Style', 'pushbutton',...
    'String', 'Analyse trajectories','FontWeight', 'bold', ...
    'Position', [Position_Width Position_Height(1) PushButtonSize]);

h.Plot_trajectories = uicontrol(h.Panel_Action, 'Style', 'checkbox',...
    'Value', 0,...
    'Position', [Position_Width_checkbox(1) Position_Height(2) CheckBoxSize]);

uicontrol(h.Panel_Action,'Style','text',...
    'String','Plot trajectories',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width_checkbox(2) Position_Height(2) TextSize]);

h.SaveForTesseler = uicontrol(h.Panel_Action, 'Style', 'pushbutton',...
    'String', 'Save filtered localizations',...
    'Position', [Position_Width Position_Height(4) PushButtonSize]);

h.PlotPreviousAnalysis = uicontrol(h.Panel_Action, 'Style', 'pushbutton',...
    'String', 'Plot previous analysis',...
    'Position', [Position_Width Position_Height(6) PushButtonSize]);

h.DataTypePlot = uicontrol(h.Panel_Action, 'Style', 'popupmenu',...
    'String', {'D distribution', 'MSD curve', 'Trajectories plot (all)', 'Trajectories plot (populations)'},...
    'Position', [Position_Width Position_Height(7) PopupmenuSize]);


%% Panel 4 : Results of the analysis (number of tracks, etc.)
%% ===========================================================

% Define the Panel

NLines_Panel_4 = 3;
PanelWidth_4 = ControlPanel_Width-2*Side_Border;
PanelHeight_4 = PanelBorder_top + PanelBorder_bottom + round(NLines_Panel_4*Panel_Line_Height);

Panel_StartPosition = [Side_Border, ...
    ControlPanel_Height - Height_Border - ...
    TextSize_FolderName(2) - ...
    3*InterPanelDistance_Height - ...
    PanelHeight_1 - ...
    PanelHeight_2 - ...
    PanelHeight_4];
Panel_Size = [PanelWidth_4 PanelHeight_4];

h.Panel_Results = uipanel(h.sptPALM_ControlPanel, 'Title', 'Statistics',...
    'Position', [Panel_StartPosition Panel_Size], 'FontWeight', 'bold');

% Define the size of the objects that are in the Panel

EditSize = [45, Edit_height];
TextSize = [220 Text_height];

% Define the position of the objects in the Panel

Width_Separation = floor((PanelWidth_4-2*(TextSize(1)+EditSize(1)))/5);

Position_Width = [Width_Separation, ...
    2*Width_Separation + TextSize(1), ...
    3*Width_Separation + TextSize(1) + EditSize(1), ...
    4*Width_Separation + 2*TextSize(1) + EditSize(1)];

Position_Height = [PanelHeight_4 - PanelBorder_top - Panel_Line_Height, ...
    PanelHeight_4 - PanelBorder_top - 2*Panel_Line_Height, ...
    PanelHeight_4 - PanelBorder_top - 3*Panel_Line_Height, ...
    PanelHeight_4 - PanelBorder_top - 4*Panel_Line_Height];

% line1

uicontrol(h.Panel_Results, 'Style', 'text',...
    'String', 'Number of files loaded',...
    'HorizontalAlignment', 'right',...
    'Position', [Position_Width(1) Position_Height(1) TextSize]);

h.NMovies = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(2) Position_Height(1) EditSize]);

uicontrol(h.Panel_Results,'Style','text',...
    'String','Number of trajectories loaded',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(3) Position_Height(1) TextSize]);

h.NTrajectories = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(4) Position_Height(1) EditSize]);

% line2

uicontrol(h.Panel_Results,'Style','text',...
    'String','Number of trajectories after filtering',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(1) Position_Height(2) TextSize]);

h.NTrajectoriesFiltered = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(2) Position_Height(2) EditSize]);

uicontrol(h.Panel_Results,'Style','text',...
    'String','Number of trajectories found in ROI',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(3) Position_Height(2) TextSize]);

h.NTrajectoriesROI = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(4) Position_Height(2) EditSize]);

% line3

% uicontrol(h.Panel_Results,'Style','text',...
%     'String','Number of trajectories used for MSD',...
%     'HorizontalAlignment','right',...
%     'Position',[Position_Width(1) Position_Height(3) TextSize]);
% 
% h.NTrajectoriesMSD = uicontrol(h.Panel_Results, 'Style', 'edit',...
%     'String', '0',...
%     'Position', [Position_Width(2) Position_Height(3) EditSize]);

uicontrol(h.Panel_Results,'Style','text',...
    'String','Number of trajectories used for Diff',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(1) Position_Height(3) TextSize]);

h.NTrajectoriesDiff = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(2) Position_Height(3) EditSize]);

uicontrol(h.Panel_Results,'Style','text',...
    'String','Density of tracks in ROI (/um^2)',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(3) Position_Height(3) TextSize]);

h.TrackDensity = uicontrol(h.Panel_Results, 'Style', 'edit',...
    'String', '0',...
    'Position', [Position_Width(4) Position_Height(3) EditSize]);


%% Panel 5 : Interactive tool to super-impose movies and tracks -
%% optimization of the MTT tracking parameters
%% ===========================================

% Define the Panel

NLines_Panel_5 = 8;
PanelWidth_5 = ControlPanel_Width - 2*Side_Border;
PanelHeight_5 = PanelBorder_top + PanelBorder_bottom + round(NLines_Panel_5*Panel_Line_Height);

Panel_StartPosition = [Side_Border, ...
    ControlPanel_Height - Height_Border - ...
    TextSize_FolderName(2) - ...
    4*InterPanelDistance_Height - ...
    PanelHeight_1 - ...
    PanelHeight_2 - ...
    PanelHeight_4 - ...
    PanelHeight_5];
Panel_Size = [PanelWidth_5 PanelHeight_5];

h.Panel_Visualization = uipanel(h.sptPALM_ControlPanel, 'Title', 'Visualization tool',...
    'Position', [Panel_StartPosition Panel_Size], 'FontWeight', 'bold');

% Define the size of the objects that are in the Panel

EditSize = [45, Edit_height];
EditSize_movie_name = [100, Edit_height];
TextSize_long = [130 Text_height];
TextSize_short = [70 Text_height];
SliderSize = [280, Slider_height];
PushButtonSize = [120,PushButton_height];

% Define the position of the objects in the Panel

Width_Separation = floor((PanelWidth_5 - SliderSize(1) - EditSize(1) - TextSize_long(1))/5);

Position_Height = [PanelHeight_5 - PanelBorder_top - 1.5*Panel_Line_Height, ...
    PanelHeight_5 - PanelBorder_top - 2.5*Panel_Line_Height, ...
    PanelHeight_5 - PanelBorder_top - 3.5*Panel_Line_Height, ...
    PanelHeight_5 - PanelBorder_top - 4.5*Panel_Line_Height, ...
    PanelHeight_5 - PanelBorder_top - 5.5*Panel_Line_Height, ...
    PanelHeight_5 - PanelBorder_top - 6.5*Panel_Line_Height, ...
    PanelHeight_5 - PanelBorder_top - 7.5*Panel_Line_Height];

% line1

Position_Width = [Width_Separation, ...
    2*Width_Separation + PushButtonSize(1), ...
    3*Width_Separation + 2*PushButtonSize(1), ...
    4*Width_Separation + TextSize_long(1) + 2*PushButtonSize(1)];

h.LoadMovie = uicontrol(h.Panel_Visualization, 'Style', 'pushbutton',...
    'String', 'Load movie',...
    'Position', [Position_Width(1) Position_Height(1) PushButtonSize]);

h.LoadTraj = uicontrol(h.Panel_Visualization, 'Style', 'pushbutton',...
    'String', 'Load trajectories',...
    'Position', [Position_Width(2) Position_Height(1) PushButtonSize]);

uicontrol(h.Panel_Visualization,'Style','text',...
    'String','Minimum track length',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(3) Position_Height(1) TextSize_long]);

h.MinTrackLength = uicontrol(h.Panel_Visualization, 'Style', 'edit',...
    'String', '1',...
    'Position', [Position_Width(4) Position_Height(1) EditSize]);

% line2

Position_Width = [Width_Separation, ...
    2*Width_Separation + PushButtonSize(1)];

h.CreateROI = uicontrol(h.Panel_Visualization, 'Style', 'pushbutton',...
    'String', 'Create ROI',...
    'Position', [Position_Width(1) Position_Height(2) PushButtonSize]);

h.DeleteROI = uicontrol(h.Panel_Visualization, 'Style', 'pushbutton',...
    'String', 'Delete ROI',...
    'Position', [Position_Width(2) Position_Height(2) PushButtonSize]);

% line3

Position_Width = [Width_Separation, ...
    2*Width_Separation + TextSize_long(1), ...
    3*Width_Separation + TextSize_long(1) + SliderSize(1)];

uicontrol(h.Panel_Visualization,'Style','text',...
    'String','Select frame ',...
    'HorizontalAlignment','center',...
    'Position',[Position_Width(1) Position_Height(3) TextSize_long]);

h.Slider_SelectFrame = uicontrol(h.Panel_Visualization,'Style','slider',...
    'Min', 1, 'Max', 10, 'Value', 1,...
    'Position',[Position_Width(2) Position_Height(3) SliderSize],...
    'SliderStep', [1/10,1/10],...
    'Visible', 'on');

h.Edit_SelectFrame = uicontrol(h.Panel_Visualization, 'Style', 'edit',...
    'String', '1',...
    'Position', [Position_Width(3) Position_Height(3) EditSize]);

% line4

Position_Width = [Width_Separation, ...
    2*Width_Separation + TextSize_long(1), ...
    3*Width_Separation + TextSize_long(1) + SliderSize(1)];

uicontrol(h.Panel_Visualization,'Style','text',...
    'String','Contrast (upper limit) ',...
    'HorizontalAlignment','center',...
    'Position',[Position_Width(1) Position_Height(4) TextSize_long]);

h.Slider_UpperContrast = uicontrol(h.Panel_Visualization,'Style','slider',...
    'Min', 1, 'Max', 10, 'Value', 1,...
    'Position',[Position_Width(2) Position_Height(4) SliderSize],...
    'SliderStep', [1/10,1/10],...
    'Visible', 'on');

h.Edit_UpperContrast = uicontrol(h.Panel_Visualization, 'Style', 'edit',...
    'String', '1',...
    'Position', [Position_Width(3) Position_Height(4) EditSize]);

% line5

Position_Width = [Width_Separation, ...
    2*Width_Separation + TextSize_long(1), ...
    3*Width_Separation + TextSize_long(1) + SliderSize(1)];

uicontrol(h.Panel_Visualization,'Style','text',...
    'String','Contrast (lower limit) ',...
    'HorizontalAlignment','center',...
    'Position',[Position_Width(1) Position_Height(5) TextSize_long]);

h.Slider_LowerContrast = uicontrol(h.Panel_Visualization,'Style','slider',...
    'Min', 1, 'Max', 10, 'Value', 1,...
    'Position',[Position_Width(2) Position_Height(5) SliderSize],...
    'SliderStep', [1/10,1/10],...
    'Visible', 'on');

h.Edit_LowerContrast = uicontrol(h.Panel_Visualization, 'Style', 'edit',...
    'String', '1',...
    'Position', [Position_Width(3) Position_Height(5) EditSize]);

% line7

Width_Separation = floor((PanelWidth_5 - PushButtonSize(1) - 2*EditSize(1) - EditSize_movie_name(1) - 3*TextSize_short(1))/8);

Position_Width = [Width_Separation, ...
    2*Width_Separation + PushButtonSize(1), ...
    3*Width_Separation + PushButtonSize(1) + TextSize_short(1), ...
    4*Width_Separation + PushButtonSize(1) + TextSize_short(1) + EditSize(1), ...
    5*Width_Separation + PushButtonSize(1) + 2*TextSize_short(1) + EditSize(1), ...
    6*Width_Separation + PushButtonSize(1) + 2*TextSize_short(1) + 2*EditSize(1), ...
    7*Width_Separation + PushButtonSize(1) + 3*TextSize_short(1) + 2*EditSize(1)];

h.SaveMovie = uicontrol(h.Panel_Visualization, 'Style', 'pushbutton',...
    'String', 'Save movie',...
    'Position', [Position_Width(1) Position_Height(7) PushButtonSize]);

uicontrol(h.Panel_Visualization,'Style','text',...
    'String','First frame',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(2) Position_Height(7) TextSize_short]);

h.FirstFrame = uicontrol(h.Panel_Visualization, 'Style', 'edit',...
    'String', '',...
    'Position', [Position_Width(3) Position_Height(7) EditSize]);

uicontrol(h.Panel_Visualization,'Style','text',...
    'String','Last frame',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(4) Position_Height(7) TextSize_short]);

h.LastFrame = uicontrol(h.Panel_Visualization, 'Style', 'edit',...
    'String', '',...
    'Position', [Position_Width(5) Position_Height(7) EditSize]);

uicontrol(h.Panel_Visualization,'Style','text',...
    'String','Movie title',...
    'HorizontalAlignment','right',...
    'Position',[Position_Width(6) Position_Height(7) TextSize_short]);

h.MovieName = uicontrol(h.Panel_Visualization, 'Style', 'edit',...
    'String', 'TrajMovie.avi',...
    'Position', [Position_Width(7) Position_Height(7) EditSize_movie_name]);


%% Panel 6 : Simulations
%% =====================

% Define the Panel

NLines_Panel_6 = 4;
PanelWidth_6 = ControlPanel_Width-2*Side_Border;
PanelHeight_6 = PanelBorder_top + PanelBorder_bottom + round(NLines_Panel_6*Panel_Line_Height);

Panel_StartPosition = [Side_Border, ...
    ControlPanel_Height - Height_Border - ...
    TextSize_FolderName(2) - ...
    5*InterPanelDistance_Height - ...
    PanelHeight_1 - ...
    PanelHeight_2 - ...
    PanelHeight_4 - ...
    PanelHeight_5 - ...
    PanelHeight_6];
Panel_Size = [PanelWidth_6 PanelHeight_6];

h.Panel_Simulation = uipanel(h.sptPALM_ControlPanel, 'Title', 'Simulation of sptPALM experiments',...
    'Position', [Panel_StartPosition Panel_Size], 'FontWeight', 'bold');

% Define the size of the objects that are in the Panel

EditSize = [45, Edit_height];
PushButtonSize_small = [180,PushButton_height];
PushButtonSize_long = [250,PushButton_height];
CheckBoxSize = [15, CheckBox_height];
TextSize = [130 Text_height];

% Define the position of the objects in the Panel


Width_Separation_line_1_2 = floor((PanelWidth_6-EditSize(1)-TextSize(1)-2*PushButtonSize_small(1))/7);
Width_Separation_line_3 = floor((PanelWidth_6-EditSize(1)-TextSize(1)-PushButtonSize_long(1))/4);

Position_Height = [PanelHeight_6 - PanelBorder_top - Panel_Line_Height, ...
    PanelHeight_6 - PanelBorder_top - 2*Panel_Line_Height, ...
    PanelHeight_6 - PanelBorder_top - 3*Panel_Line_Height, ...
    PanelHeight_6 - PanelBorder_top - 4*Panel_Line_Height];

% line1

Position_Width = [Width_Separation_line_1_2, ...
    2*Width_Separation_line_1_2 + EditSize(1), ...
    3*Width_Separation_line_1_2 + EditSize(1) + TextSize(1), ...
    4*Width_Separation_line_1_2 + 2*EditSize(1) + TextSize(1), ...
    5*Width_Separation_line_1_2 + 2*EditSize(1) + 2*TextSize(1), ...
    6*Width_Separation_line_1_2 + 3*EditSize(1) + 2*TextSize(1)];

h.Simulation_Diff1 = uicontrol(h.Panel_Simulation, 'Style', 'edit',...
    'String', '',...
    'Position', [Position_Width(1) Position_Height(1) EditSize]);

uicontrol(h.Panel_Simulation,'Style','text',...
    'String','Diff coeff #1 (um^²/s)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(1) TextSize]);

h.Simulation_Diff2 = uicontrol(h.Panel_Simulation, 'Style', 'edit',...
    'String', '',...
    'Position', [Position_Width(3) Position_Height(1) EditSize]);

uicontrol(h.Panel_Simulation,'Style','text',...
    'String','Diff coeff #2 (um^²/s)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(4) Position_Height(1) TextSize]);

h.Simulation_Fraction = uicontrol(h.Panel_Simulation, 'Style', 'edit',...
    'String', '',...
    'Position', [Position_Width(5) Position_Height(1) EditSize]);

uicontrol(h.Panel_Simulation,'Style','text',...
    'String','Fraction of prot1 (%)',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(6) Position_Height(1) TextSize]);

% line2

Position_Width = [Width_Separation_line_1_2, ...
    2*Width_Separation_line_1_2 + EditSize(1), ...
    3*Width_Separation_line_1_2 + EditSize(1) + TextSize(1), ...
    4*Width_Separation_line_1_2 + EditSize(1) + TextSize(1) + PushButtonSize_small(1)];

h.Simulation_NFrames = uicontrol(h.Panel_Simulation, 'Style', 'edit',...
    'String', '1000',...
    'Position', [Position_Width(1) Position_Height(2) EditSize]);

uicontrol(h.Panel_Simulation,'Style','text',...
    'String','Number of frames',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(2) Position_Height(2) TextSize]);

h.Simulation_EmissionParameters = uicontrol(h.Panel_Simulation, 'Style', 'pushbutton',...
    'String', 'Change emission parameters',...
    'Position', [Position_Width(3) Position_Height(2) PushButtonSize_small]);

h.Simulation_AquisitionParameters = uicontrol(h.Panel_Simulation, 'Style', 'pushbutton',...
    'String', 'Change aquisition parameters',...
    'Position', [Position_Width(4) Position_Height(2) PushButtonSize_small]);

% line3

Position_Width = [Width_Separation_line_3, ...
    2*Width_Separation_line_3 + PushButtonSize_long(1), ...
    2*Width_Separation_line_3 + PushButtonSize_long(1) + CheckBoxSize(1)];

h.LaunchSimulation = uicontrol(h.Panel_Simulation, 'Style', 'pushbutton',...
    'String', 'Lauch simulation',...
    'Position', [Position_Width(1) Position_Height(4) PushButtonSize_long]);

h.Simulation_Verbose = uicontrol(h.Panel_Simulation, 'Style', 'checkbox',...
    'Value', 0,...
    'Position', [Position_Width(2) Position_Height(4) CheckBoxSize]);

uicontrol(h.Panel_Simulation,'Style','text',...
    'String','Display all images',...
    'HorizontalAlignment','left',...
    'Position',[Position_Width(3) Position_Height(4) TextSize]);

end